name: Android Build

on: [push, pull_request]

jobs:
  build:

    runs_on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      -name: Set up JDK
       uses: actions/setup-java@v1
       with:
         java-version:1.8

      -name: Run Android Build
       run: ./Client/gradlew build

      -name: Run Android JunitTests
       run: ./Client/gradlew test

      -name: Run Android EspressoTests 
       run: ./Client/gradlew connectedAndroidTest

      -name: Run DataProxyBuild
       run: ./DataProxy/gradlew build

      -name: Run DataProxyTests
       run: ./DataProxy/gradlew test



